# taken from https://github.com/nix-community/go-nix/blob/main/.golangci.yml
linters:
    enable:
        - errname
        - errorlint
        - exhaustive
        - gci
        - gochecknoglobals
        - gochecknoinits
        - goconst
        - godot
        - gofumpt
        - goheader
        - goimports
        - gosec
        - importas
        - intrange
        - ireturn
        - lll
        - makezero
        - mirror
        - misspell
        - nakedret
        - nestif
        - nilerr
        - nilnil
        - nlreturn
        - noctx
        - nolintlint
        - perfsprint
        - prealloc
        - predeclared
        - revive
        - rowserrcheck
        - stylecheck
        - tagalign
        - tagliatelle
        - tenv
        - testifylint
        - testpackage
        - thelper
        - unconvert
        - unparam
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
